// src/pages/apartment/forandring.tsx
import React from 'react';
import {Heading, Hr, PageContainer, Paragraph, SubHeading} from '../page-container';
import {LinkTo} from '../contacts/contact-card';
import contacts from "../contacts/contacts.json";
import {Link, Typography} from '@material-ui/core';

export const Forandring = () => {
  return (
    <PageContainer>
      <Heading>
        Förändring i lägenheten
      </Heading>

      <Paragraph>
        Mindre förändringar får göras i lägenheten. Du får t ex lägga nya golv, sätta upp nya skåp eller byta ut vitvaror i kök och badrum.
        Alla arbeten skall utföras fackmannamässigt. Mer omfattande förändringar kräver dock styrelsens tillstånd, t ex om Du vill ta ner en
        vägg, dra nya rör i kök och badrum. Ibland kan det också behövas bygglov för att utföra vissa åtgärder i lägenheten. Kontakta alltid
        styrelsen innan Du sätter igång! Tänk också på att ta hänsyn till de omkringboende när Du utför bullerstörande arbeten i lägenheten.
        Dessa bör i första hand utföras under dagtid.
      </Paragraph>

      <Paragraph>
        Bostadsrättshavaren får inte utan styrelsens tillstånd utföra åtgärder i lägenheten som innefattar
      </Paragraph>

      <ul>
        <li>
          <Typography variant={'body1'}>Ingrepp i bärande konstruktion</Typography>
        </li>

        <li>
          <Typography variant={'body1'}>Ändring av eller anslutning till befintliga ledningar för avlopp, värme, gas, vatten, ventilation
            eller</Typography>
        </li>

        <li>
          <Typography variant={'body1'}>Annan väsentlig förändring av lägenheten</Typography>
        </li>
      </ul>

      <Hr/>

      <SubHeading>
        SÅ HÄR ANSÖKER DU
      </SubHeading>

      <Paragraph>
        För att ansöka om att ändringar av din bostad behöver du fylla i <Link href="../../assets/bostadsandring.pdf">Ansökan om tillstånd
        för ändring i bostadsrättslägenhet</Link>. Ansökan
        skickas till <LinkTo type={'Mail'}>{contacts.styrelsen.email}</LinkTo>
        <br/><br/>
        Styrelsen får inte vägra att medge tillstånd till en åtgärd som avses i första stycket om inte åt-gärden är till påtaglig skada
        eller olägenhet för föreningen eller annan medlem. Bostadsrätts-havaren svarar för att erforderliga myndighetstillstånd erhålls.
        Förändringar ska alltid utföras på ett fackmannamässigt sätt.
      </Paragraph>
    </PageContainer>
  );
};

// src/app/your-apartment/forandring/forandring.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-forandring',
  templateUrl: './forandring.component.html',
  styleUrls: ['./forandring.component.scss']
})
export class ForandringComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}

<div class="container pt-4">
  <div class="card">
    <h1 class="card-header">
      Förändring i lägenheten
    </h1>

    <div class="card-body">
      <p>
        Bostadsrättshavaren får inte utan styrelsens tillstånd utföra åtgärder i lägenheten som innefattar
      </p>
      <p>
        - Ingrepp i bärande konstruktion
      </p>
      <p>
        - Ändring av eller anslutning till befintliga ledningar för avlopp, värme, gas, vatten, ventilation eller
      </p>
      <p>
        - Annan väsentlig förändring av lägenheten
      </p>

      <h4 class="card-title">
        SÅ HÄR ANSÖKER DU
      </h4>
      <p>
        För att ansöka om att ändringar av din bostad behöver du fylla i nedanstående ansökningsblankett. Ansökan skickas till
        <a href="mailto:flygplansfabriken@gmail.com">flygplansfabriken@gmail.com</a>
      </p>
      <p>
        Styrelsen får inte vägra att medge tillstånd till en åtgärd som avses i första stycket om inte åt-gärden är till
        påtaglig skada eller olägenhet för föreningen eller annan medlem. Bostadsrätts-havaren svarar för att erforderliga
        myndighetstillstånd erhålls. Förändringar ska alltid utföras på ett fackmannamässigt sätt.
      </p>
    </div>
  </div>
</div>
