// src/app/your-apartment/andrahandsuthyrning/andrahandsuthyrning.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-andrahandsuthyrning',
  templateUrl: './andrahandsuthyrning.component.html',
  styleUrls: ['./andrahandsuthyrning.component.scss']
})
export class AndrahandsuthyrningComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}

<section class="container pt-4">
  <div class="card">
    <h1 class="card-header">Andrahandsuthyrning</h1>
    <div class="card-body">
      <h4 class="card-title">Regler</h4>
      <p>
        Regler gällande andrahandsuthyrning finns i föreningens <a href="">stadgar</a>.
      </p>
      <strong>Så här ansöker du</strong>
      <p>
        För att ansöka om att hyra ut din bostad i andra hand behöver du fylla i nedanstående ansökningsblankett.
        Blanketten mailas därefter till <a href="mailto:flygplansfabriken@gmail.com"></a>. Godkänd uthyrningstid är max
        två år.
        Handläggningstiden är ca 30 dagar.
      </p>
      <strong>
        OBS! Lägenhetsnumret som ska anges på blanketten är bostadsrättsföreningens lägenhetnummer, alltså inte det som
        Skatteverket har registretat och som står på din dörr.
      </strong>
      <br>
      <div>
        <strong class="text-primary">
          <a href="">
            Blankett för andrahandsuthyrning (.pdf)
          </a>
        </strong>
      </div>
      <br>
      <h4>
        Avgift i samband med andrahandsuthyrning
      </h4>
      <p>
        Den 1 juli 2014 trädde ändringar i bostadsrättslagen i kraft gällande nya regler för andrahandsupplåtelser av
        bostadsrättslägenheter.
      </p>
      <p>
        Förändringen innebär i korthet att det blir generösare regler för en bostadsrättshavare som vill hyra ut sin
        lägenhet i andrahand samt att bostadsrättsföreningen får en möjlighet att ta ut en avgift för
        andrahandsupplåtelsen. För att bostadsrättsföreningen ska få ta ut avgiften krävs dock att det anges i
        föreningens
        stadgar. Det är alltså nödvändigt med en stadgeändring om föreningen önskar ta ut en avgift för
        andrahandsupplåtelse.
      </p>
      <p>Brf Flygplansfabriken har under ett ordinarie och ett extra årsmöte beslutat att ändra sina stadgar i enlighet
        med
        lagändringen. Brf Flygplansfabriken kommer med stöd av föreningens stadgar (fr.o.m. 2018-03-01) ta ut en
        månadsavgift för varje påbörjad månad som andrahandsuthyrning pågår. Avgiften för dig som hyr ut i andra hand är
        10
        % av gällande prisbasbelopp per helår. Avgiften utgår för varje påbörjad månad av andrahandsuthyrningen.
        Månadsavgiften för andrahandsuthyrning kommer att läggas till på månadsavin för föreningsavgiften under den
        period
        du ansökt om att hyra ut i andra hand.</p>

      <p>Exempel: Prisbasbeloppet för år 2018 är 45 500 kr. Den maximala avgiften för andrahandsuthyrning är 4 500 kr
        under
        år 2018, det innebär en avgift om 375 kr per månad.</p>
      <p>
        <strong>
          Observera att du fortfarande måste ansöka hos styrelsen om att hyra ut din lägenhet i enlighet med föreningens
          stadgar. Andrahandsuthyrning utan tillstånd är ett brott mot föreningens stadgar och kan leda till att
          nyttjanderätten för lägenheten förverkas.
        </strong>
      </p>
    </div>
  </div>
</section>

// src/pages/apartment/andrahandsuthyrning.tsx
import React from 'react';
import {Heading, Hr, PageContainer, Paragraph, SubHeading, Warn} from '../page-container';
import {Link} from '@material-ui/core';
import {LinkTo} from '../contacts/contact-card';
import andrahand from "../../assets/andrahand.pdf";

export const Andrahandsuthyrning = () => {
  return (
    <PageContainer>
      <Heading>
        Regler
      </Heading>

      <Paragraph>
        Regler gällande andrahandsuthyrning finns i föreningens <Link href="/#/styrelsen/document">Stadgar</Link>
      </Paragraph>

      <Hr/>

      <SubHeading>
        Så här ansöker du
      </SubHeading>

      <Paragraph>
        För att ansöka om att hyra ut din bostad i andra hand behöver du fylla i <Link href={andrahand}>ansökningsblankett</Link>.
        <br/><br/>
        Blanketten mailas därefter till <LinkTo type={'Mail'}>andrahand@brf-flygplansfabriken.se</LinkTo>. Godkänd uthyrningstid är max ett år. Handläggningstiden är ca 30
        dagar.
      </Paragraph>
      <Warn>
        OBS! Lägenhetsnumret som ska anges på blanketten är bostadsrättsföreningens lägenhetnummer, alltså inte det som Skatteverket har
        registretat och som står på din dörr.
      </Warn>

      <SubHeading>
        Avgift i samband med andrahandsuthyrning
      </SubHeading>

      <Paragraph>
        Brf Flygplansfabriken kommer med stöd av föreningens stadgar (fr.o.m. 2018-03-01) ta ut en månadsavgift för varje påbörjad månad som
        andrahandsuthyrning pågår. Avgiften för dig som hyr ut i andra hand är 10 % av gällande prisbasbelopp per helår. Avgiften utgår för
        varje påbörjad månad av andrahandsuthyrningen. Månadsavgiften för andrahandsuthyrning kommer att läggas till på månadsavin för
        föreningsavgiften under den period du ansökt om att hyra ut i andra hand.
        <br/><br/>
        Exempel: Prisbasbeloppet för år 2018 är 45 500 kr. Den maximala avgiften för andrahandsuthyrning är 4 500 kr under år 2018, det
        innebär en avgift om 375 kr per månad.
        <br/><br/>
        Observera att du fortfarande måste ansöka hos styrelsen om att hyra ut din lägenhet i enlighet med föreningens stadgar.
        Andrahandsuthyrning utan tillstånd är ett brott mot föreningens stadgar och kan leda till att nyttjanderätten för lägenheten
        förverkas.
      </Paragraph>
    </PageContainer>
  );
};
