// src/pages/report/felanmalan.tsx
import React from "react";
import {
    Heading,
    Hr,
    PageContainer,
    Paragraph,
    SubHeading,
    Warn,
} from "../page-container";
import { LinkTo } from "../contacts/contact-card";
import contacts from "../contacts/contacts.json";
import { Link } from "@mui/material";

export const Felanmalan = () => {
    return (
        <PageContainer>
            <Heading>Felanmälan</Heading>

            <Paragraph>
                Nedan finner du information om vart du ska vända dig om du vill
                göra en felanmälan på något som hör till fastigheten eller din
                bostad. Det åligger var och en att anmäla ett fel som man
                upptäckt.
                <br />
                <br />
                Föreningen har för närvarande avtal med bolaget
                Fastighetsskötsel AB rörande fastighetsskötsel.
                Fastighetsskötsel AB har en veckovis tillsyn av fastigheten. Då
                åtgärdas också de fel som är anmälda, såvida felet inte är av
                akut karaktär.
                <br />
                <br />
                Är du osäker på något eller om du har du några frågor kring
                felanmälan är du välkommen att kontakta styrelsen på{" "}
                <LinkTo type={"Mail"}>{contacts.styrelsen.email}</LinkTo>
            </Paragraph>

            <Hr />

            <SubHeading>Fel i fastigheten – Port, dörr mm.</SubHeading>

            <Paragraph>
                <b>Kontakta</b> <br /> {contacts.Fastighetsservice.name}
                <br />
                Telefon:{" "}
                <LinkTo type={"Tel"}>
                    {contacts.Fastighetsservice.phone[0].number}
                </LinkTo>{" "}
                ({contacts.Fastighetsservice.phone[0].openingHours})
                <br />
                Webbsida för felamnälan:{" "}
                <Link
                    color={"secondary"}
                    href={contacts.Fastighetsservice.homePage}
                >
                    {contacts.Fastighetsservice.homePage}
                </Link>
                <br />
                E-post:{" "}
                <LinkTo type={"Mail"}>
                    {contacts.Fastighetsservice.email}
                </LinkTo>
                <br />
                Du kan också kontakta styrelsen E-post:{" "}
                <LinkTo type={"Mail"}>{contacts.styrelsen.email}</LinkTo>
                <br />
                <br />
                När du har gjort din felanmälan gällande fel i gemensamma
                utrymmen kan det vara bra att sätta upp en lapp på anslagstavlan
                om att felanmälan är gjord som en information till dina grannar.
            </Paragraph>

            <Hr />

            <SubHeading>Felanmälan jour – Ärenden av akut karaktär</SubHeading>

            <Paragraph>
                Telefon:{" "}
                <LinkTo type={"Tel"}>
                    {contacts.Fastighetsservice.phone[0].number}
                </LinkTo>
                , välj 1, ({contacts.Fastighetsservice.phone[0].openingHours})
                <br />
                Telefon:{" "}
                <LinkTo type={"Tel"}>
                    {contacts.Fastighetsservice.phone[1].number}
                </LinkTo>{" "}
                ({contacts.Fastighetsservice.phone[1].openingHours})
            </Paragraph>
            <Warn>
                OBS! Är felet du anmäler verkligen akut? Föreningen får extra
                kostnader vid akut felavhjälpning
            </Warn>

            <Hr />

            <SubHeading>Fel i din lägenhet</SubHeading>

            <Paragraph>
                <b>Kontakta</b> <br />
                Fastighetsskötsel.
                <br />
                Webbsida för felamnälan:{" "}
                <Link href={contacts.Fastighetsservice.homePage}>
                    {contacts.Fastighetsservice.homePage}
                </Link>
                <br />
                Telefon:{" "}
                <LinkTo type={"Tel"}>
                    {contacts.Fastighetsservice.phone[0].number}
                </LinkTo>{" "}
                ({contacts.Fastighetsservice.phone[0].openingHours})
                <br />
                E-post:{" "}
                <LinkTo type={"Mail"}>
                    {contacts.Fastighetsservice.email}
                </LinkTo>
                <br />
            </Paragraph>

            <Warn>
                Observera att bostadsrättsinnehavaren ansvarar för fel på sin
                enskilda lägenhet. Det går bra att kontakta Fastighetsskötsel,
                men om felet inte täcks av föreningens ansvar debiteras
                bostadsrättsinnehavaren för arbetskostnaden.
            </Warn>

            <Hr />

            <SubHeading>Fel på hiss</SubHeading>

            <Paragraph>
                <b>Kontakta</b> <br /> {contacts.elevator.name}
                <br />
                Telefon:{" "}
                <LinkTo type={"Tel"}>
                    {contacts.elevator.phone[0].number}
                </LinkTo>
            </Paragraph>

            <Hr />

            <SubHeading>Borttappade nycklar</SubHeading>

            <Paragraph>
                Alla ärende gällande nycklar, kontakta{" "}
                {contacts.lockService.name}.
                <br />
                Telefon:{" "}
                <LinkTo type={"Tel"}>
                    {contacts.lockService.phone[0].number}
                </LinkTo>
                <br />
                Email:{" "}
                <LinkTo type={"Mail"}>{contacts.lockService.email}</LinkTo>
            </Paragraph>

            <Hr />

            <SubHeading>Felparkerad bil</SubHeading>

            <Paragraph>
                Kontakta {contacts.parking.name}
                <br />
                Telefon:{" "}
                <LinkTo type={"Tel"}>{contacts.parking.phone[0].number}</LinkTo>
            </Paragraph>
        </PageContainer>
    );
};

// src/app/your-apartment/felanmalan/felanmalan.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-felanmalan',
  templateUrl: './felanmalan.component.html',
  styleUrls: ['./felanmalan.component.scss']
})
export class FelanmalanComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}

<div class="container">
  <div class="card">
    <h1 class="card-header">Gör en felanmälan</h1>

    <div class="card-body">
      <p>
        Nedan finner du information om vart du ska vända dig om du vill göra en felanmälan på något som hör till
        fastigheten eller din bostad. Det åligger var och en att anmäla ett fel som man upptäckt.
      </p>

      <p>
        Föreningen har för närvarande avtal med bolaget MFS fastighetsservice rörande fastighetsskötsel. MFS
        fastighetsservice har en veckovis tillsyn av fastigheten. Då åtgärdas också de fel som är anmälda, såvida felet
        inte är av akut karaktär.
      </p>

      <p>
        Är du osäker på något eller om du har du några frågor kring felanmälan är du välkommen att kontakta styrelsen på
        <a href="mailto:styrelse@brf-flygplansfabriken.se">styrelse@brf-flygplansfabriken.se.</a>
      </p>

      <h4 class="card-title">Fel i fastigheten – Port, dörr mm.</h4>

      <p>
        Kontakta MFS fastighetsservice.
        <br>
        Telefon: <a href="tel:08-645 17 00">08-645 17 00</a> <b>(vardagar 08.00-16.00)</b>
      </p>
      <p>
        Webbsida för felamnälan:
        <a href="http://www.mfsfastighetsservice.se/felanmalan">www.mfsfastighetsservice.se/felanmalan</a>
        <br>
        E-post: <a href="mailto:mfs@mfsfastighetsservice.se">mfs@mfsfastighetsservice.se</a>
      </p>

      <p>
        <b>Du kan också kontakta styrelsen</b>
        <br>
        E-post: <a href="mailto:styrelse@brf-flygplansfabriken.se">styrelse@brf-flygplansfabriken.se</a>
        <br>
        När du har gjort din felanmälan gällande fel i gemensamma utrymmen kan det vara bra att sätta upp en lapp på
        anslagstavlan om att felanmälan är gjord som en information till dina grannar.
      </p>

      <h4 class="card-title">Felanmälan jour – Ärenden av akut karaktär</h4>
      <p>
        Telefon: <a href="tel:08 - 645 17 45">08 - 645 17 45</a>
        <br>
        Jouren är öppen då ordinarie fastighetsskötare inte är i tjänst: vardagar <b>kl 16:00 - 08:00</b>, samt dygnet
        runt på
        helger och helgdagar.
        <br>
        <b class="text-danger">OBS! Är felet du anmäler verkligen akut? Föreningen får extra kostnader vid akut
          felavhjälpning.</b>
      </p>

      <h4 class="card-title">Fel i din lägenhet</h4>
      <p>Observera att bostadsrättsinnehavaren ansvarar för fel på sin enskilda lägenhet. Det går bra att kontakta
        Fastighetsskötsel, men om felet inte täcks av föreningens ansvar debiteras bostadsrättsinnehavaren för
        arbetskostnaden.</p>
      <p>Är du osäker på vad du respektive föreningen ansvarar för kan du få vägledning genom att titta på
        sidan <a routerLink="/ditt-boende/underhallansvar">Underhållsansvar</a>.</p>
      <p>
        Telefon: <a href="08-645 17 00">08-645 17 00</a> <b>(vardagar 08.00-16.00)</b>
        <br>
        Webbsida för felamnälan: <a
        href="http://www.mfsfastighetsservice.se/felanmalan">www.mfsfastighetsservice.se/felanmalan</a>
        <br>
        E-post: <a href="mailto:mfs@mfsfastighetsservice.se">mfs@mfsfastighetsservice.se</a>
      </p>

      <h4 class="card-title">Vattenskada i din lägenhet</h4>
      <p>
        Om du råkar ut för vattenskada skall du alltid se till att få felet avhjälpt omedelbart. Du skall även kontakta
        ditt försäkringsbolag samt meddela styrelsen.
      </p>

      <h4 class="card-title">Fel på vattenförsörjningen</h4>
      <p>
        I vissa fall ligger fel på vattenförsörjningen utanför föreningens kontroll.
        <br>
        Om du inte har något vatten i din kran eller om trycket på vattnet är lågt rekommenderar vi att du även
        felanmäler detta till <a href="http://www.stockholmvatten.se/kundservice/kontakta-oss/felanmalan/">Stockholm
        Vatten</a>.
      </p>

      <h4 class="card-title">Fel på elförsörjningen</h4>
      <p>
        I vissa fall ligger fel på elförsörjningen utanför föreningens kontroll. För att säkerställa att elförsörjningen
        är normal rekommenderas att även felanmäla till
        <a href="http://www.fortum.com/countries/se/om-fortum/kontakt/pages/default.aspx">Fortum</a>.
      </p>

      <h4 class="card-title">Fel på vitvaror</h4>
      <p>
        Kontakta respektive leverantör. Om varan funnits i lägenheten sedan den var ny finns troligtvis instruktioner i
        din beondepärm.
      </p>

      <h4 class="card-title">Fel på hiss</h4>
      <p>
        Kontakta KONE
        <br>
        Telefon: <a href="tel:020-72 20 20">020-72 20 20</a> (dygnet runt)
      </p>

      <h4 class="card-title">Fel på Internet</h4>
      <p>
        Internet via fiber levereras för närvarande av Bredbandsbolaget. <br>Kontakta Bredbandsbolaget kundservice för
        fibertjänster för att få rätt hjälp.
        <br>
        Telefon: <a href="tel:0770-777 000">0770-777 000</a> alla dagar kl. <b>08.00–22.00</b>.
      </p>
    </div>
  </div>
</div>
