// src/pages/apartment/parkering.tsx
import React from 'react';
import {Heading, Hr, PageContainer, Paragraph, SubHeading} from '../page-container';
import {LinkTo} from '../contacts/contact-card';
import contacts from "../contacts/contacts.json";

export const Parkering = () => {
  return (
    <PageContainer>
      <Heading>Parkering</Heading>
      <Paragraph>Brf Flygplansfabriken äger och förfogar över <b>21st</b> parkeringsplatser.</Paragraph>

      <Hr/>

      <SubHeading>
        Kostnad och kösystem
      </SubHeading>

      <Paragraph>
        Parkeringsplatserna utomhus uthyres av föreningen till en kostnad av fn. <b>800 kr/mån</b>
        <br/><br/>
        För information om eventuellt lediga parkeringsplatser, kontakta Brf Ekonomen på <LinkTo
        type={'Mail'}>{contacts.accounting.email}</LinkTo> för mer information eller för att anmäla ert intresse.
      </Paragraph>
    </PageContainer>
  );
};

// src/app/your-apartment/parkering/parkering.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-parkering',
  templateUrl: './parkering.component.html',
  styleUrls: ['./parkering.component.scss']
})
export class ParkeringComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}

<div class="container pt-4">
  <div class="card">
    <h1 class="card-header">Parkering</h1>

    <div class="card-body">
      <p>Brf Flygplansfabriken äger och förfogar över <b>21st</b> parkeringsplatser.</p>
      <h4 class="card-title">Kostnad och kösystem</h4>
      <p>Parkeringsplatserna utomhus uthyres av föreningen till en kostnad av fn. <b>850 kr/mån</b></p>
      <p>
        För information om eventuellt lediga parkeringsplatser, kontakta Brf Ekonomen på
        <a href="mailto:info@brfekonomen.se">info@brfekonomen.se</a> för mer information eller för att anmäla ert
        intresse.
      </p>
    </div>
  </div>
</div>
